---
- name: setup lamp stack single node
  hosts: lamp

  roles: 
    - role: common
      become: yes
      become_method: sudo
    - app
    - role: web
      become: yes
      become_method: sudo
    - db
