---
- name: Install flask in env
  pip:
    name: "{{ pip_install }}"
    virtualenv: ~/.flask-env

- name: Display pip freeze
  shell: ". {{ flask_env }} && pip freeze"
  #shell: "pip freeze"
  register: pipfreeze

- name: Display Output
  debug: 
    msg: 
      - "pip list: {{ pipfreeze.stdout_lines }}"

