---
- name: Install packages
  apt: 
    name: "{{ packages }}"
    state: latest

- name: Upgrade pip
  pip:
    name: pip
    state: latest
    executable: pip3

- name: Configure virtualenv
  command: "python3 -m venv flask-env"

- name: Change file permission of venv
  file: 
    path: ~/flask-env
    state: directory
    owner: lamp
    group: sudo
    recurse: yes
  become: yes

- name: Activate venv
  command: ". flask-env/bin/activate"

- name: pip location
  command: "which pip"
  register: whichpip
   
- name: Display pip location
  debug: 
    msg: "{{ whichpip.stdout_lines }}"

# - name: Install flask 
#   pip:
#     name: 
#       - flask
#       - mysql-connector-python
#     state: latest
#
# - name: create requirements.txt
#   shell: "pip freeze > requirements.txt && cat requirements.txt"
#   register: require
#
# - name: Display requirements.txt
#   debug: 
#     msg: "{{ require.stdout_lines }}"

