---
- name: Update repository
  apt: 
    update_cache: yes

- name: Install Packages
  apt:
    name:  "{{ system_packages }}"
    state: latest

- name: Open https service
  firewalld:
    service: https
    permanent: true
    state: enabled
    immediate: true

- name: Open 443 port
  firewalld:
    port: 443/tcp
    permanent: true
    state: enabled
    immediate: true

- name: firewalld info
  command: "sudo firewall-cmd --info-zone=public"
  register: output

- name: Display firewalld info
  debug: 
    msg: "{{ output.stdout_lines }}"

- name: Install packages
  apt: 
    name: "{{ python_packages }}"
    state: latest

- name: Upgrade pip
  pip:
    name: pip
    state: latest
    executable: pip3

